config/routes.rb
FoodTruckMap::Application.routes.draw do
  devise_for :users,  controllers: { sessions: 'admin/sessions' }

  namespace :admin do
    resources :users
    resources :food_trucks

    get '/' => 'dashboard#index'
  end

  scope 'api' do
    resources :food_trucks
    resources :tags
  end

  root :to => 'map#index'
end

app/models/food_truck.rb
class FoodTruck < ActiveRecord::Base
  has_many :schedule_entries
  has_many :locations, through: :schedule_entries

  attr_accessible :name, :description, :twitter_username, :facebook_username, :website_url, :schedule_entries_attributes, :tag_list

  accepts_nested_attributes_for :schedule_entries, reject_if: :all_blank, allow_destroy: true

  default_scope order(:name)

  acts_as_taggable

  def type
    # TODO: update this for seattle
    self.business_type.blank? ? 'stand' : self.business_type
  end

  def status
    # TODO: fix this
    'open'
  end

  def schedule
    # TODO: allow for more than one schedule item per day
    days = {}
    %w[sunday monday tuesday wednesday thursday friday saturday].each do |day|
      # TODO: convert to find_by with rails4
      days[day] = self.schedule_entries.where('day = ?', day).first
    end
    days
  end

  def schedule_for_day(day)
    self.schedule_entries.where('day = ?', day).first
  end

  def self.active_trucks
    ScheduleEntry.where(day: Time.now.strftime("%A").downcase).where('start_time <= ? and end_time >= ?', Time.now, Time.now).map { |s| s.food_truck }
  end
end

app/controllers/admin/food_trucks_controller.rb
class Admin::FoodTrucksController < AdminController
  # GET /food_trucks
  # GET /food_trucks.json
  def index
    @food_trucks = FoodTruck.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @food_trucks }
    end
  end

  # GET /food_trucks/new
  # GET /food_trucks/new.json
  def new
    @food_truck = FoodTruck.new
    @all_tags = FoodTruck.tag_counts.collect(&:name)

    respond_to do |format|
      format.html
      format.json { render json: @food_truck }
    end
  end

  # GET /food_trucks/1/edit
  def edit
    @food_truck = FoodTruck.find(params[:id])
    @all_tags = FoodTruck.tag_counts.collect(&:name)
  end

  # POST /food_trucks
  # POST /food_trucks.json
  def create
    @food_truck = FoodTruck.new(params[:food_truck])

    respond_to do |format|
      if @food_truck.save
        format.html { redirect_to admin_food_trucks_path, notice: 'Food truck was successfully created.' }
        format.json { render json: @food_truck, status: :created, location: @food_truck }
      else
        format.html { render action: "new" }
        format.json { render json: @food_truck.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /food_trucks/1
  # PUT /food_trucks/1.json
  def update
    @food_truck = FoodTruck.find(params[:id])

    respond_to do |format|
      if @food_truck.update_attributes(params[:food_truck])
        format.html { redirect_to admin_food_trucks_path(), notice: "Food truck #{@food_truck.name} was successfully updated." }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @food_truck.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /food_trucks/1
  # DELETE /food_trucks/1.json
  def destroy
    @food_truck = FoodTruck.find(params[:id])
    @food_truck.destroy

    respond_to do |format|
      format.html { redirect_to admin_food_trucks_url, notice: "Food truck was successfully deleted." }
      format.json { head :no_content }
    end
  end
end

app/controllers/food_trucks_controller.rb
class FoodTrucksController < ApplicationController
  def index
    @food_trucks = FoodTruck.all
    render json: @food_trucks, each_serializer: FoodTruckSerializer, root: false
  end

  def show
    @food_truck = FoodTruck.find(params[:id])
    render json: @food_truck
  end
end

app/helpers/food_trucks_helper.rb
module FoodTrucksHelper
end

app/views/admin/food_trucks/_form.haml
= simple_form_for [:admin, @food_truck], html: { class: 'form-horizontal' } do |f|
  - if @food_truck.errors.any?
    #error_explanation
      %h2
        = pluralize(@food_truck.errors.count, "error")
        prohibited this food_truck from being saved:
      %ul
        - @food_truck.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :name, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.input_field :name, class: 'form-control'

  .form-group
    = f.label :tags, class: 'col-sm-2 control-label', for: :food_truck_tag_list
    .col-sm-10
      = f.input_field :tag_list, style: 'width: 100%'
      :coffee
        window.all_tags = #{@all_tags.to_json}


  .form-group
    = f.label :description, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.input_field :description, class: 'form-control', rows: 5

  .form-group
    = f.label :twitter_username, 'Twitter URL', class: 'col-sm-2 control-label'
    .col-sm-10
      = f.input_field :twitter_username, class: 'form-control'

  .form-group
    = f.label :facebook_username, 'Facebook URL', class: 'col-sm-2 control-label'
    .col-sm-10
      = f.input_field :facebook_username, class: 'form-control'

  .form-group
    = f.label :website_url, 'Website URL', class: 'col-sm-2 control-label'
    .col-sm-10
      = f.input_field :website_url, class: 'form-control'

  .row
    .col-sm-offset-2.col-sm-10
      %h4 Schedule
      %table.table.table-striped.table-bordered
        %thead
          %tr
            %th
            %th Start Time
            %th End Time
            %th Display Address
            %th Lat/Lng
            %th
        %tbody#schedule_entries
          = f.simple_fields_for :schedule_entries do |schedule_entry|
            = render 'schedule_entry_fields', f: schedule_entry
      %p= link_to_add_association 'add schedule entry', f, :schedule_entries, :'data-association-insertion-node' => 'tbody#schedule_entries', :'data-association-insertion-method' => 'append'

  .form-group.actions
    .col-sm-offset-2.col-sm-10
      = f.button :submit, 'Submit'
      - if params[:action] == 'edit'
        %p.delete-link
          = link_to 'Delete Food Truck', admin_food_truck_path, method: :delete, data: { confirm: 'Are you sure you want to delete this food truck?' }

app/views/admin/food_trucks/_schedule_entry_fields.haml
%tr.nested-fields
  %td= f.input_field :day, collection: %w[sunday monday tuesday wednesday thursday friday saturday]
  %td= f.input_field :start_time
  %td= f.input_field :end_time
  %td= f.input_field :address, style: 'width: 200px'
  %td
    = f.label :latitude, 'Lat'
    = f.input_field :latitude, style: 'width: 80px'
    %br
    = f.label :longitude, 'Lng'
    = f.input_field :longitude, style: 'width: 80px'
  %td= link_to_remove_association 'delete', f

app/views/admin/food_trucks/edit.haml
%h1
  %span.text-muted Editing Food Truck:
  %span= @food_truck.name

= render 'form'

app/views/admin/food_trucks/index.haml
%h1 Food Trucks

%p
  = link_to new_admin_food_truck_path do
    %span.glyphicon.glyphicon-plus
    New Food Truck

%table.table.table-striped.table-bordered
  %thead
    %tr
      %th Name
      %th # Schedule Entries
      %th Last Update
  %tbody
    - @food_trucks.each do |food_truck|
      %tr
        %td
          = link_to food_truck.name, edit_admin_food_truck_path(food_truck)
        %td
          = food_truck.schedule_entries.count
        %td
          = food_truck.updated_at.strftime('%b %d %Y, %H:%M')

app/views/admin/food_trucks/new.haml
%h1 New Food Truck

= render 'form'

= link_to 'Back', admin_food_trucks_path

app/views/admin/food_trucks/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_admin_food_truck_path(@admin_food_truck) %> |
<%= link_to 'Back', admin_food_trucks_path %>