config/routes.rb
FoodTruckMap::Application.routes.draw do
  devise_for :users,  controllers: { sessions: 'admin/sessions' }

  namespace :admin do
    resources :users
    resources :food_trucks

    get '/' => 'dashboard#index'
  end

  scope 'api' do
    resources :food_trucks
    resources :tags
  end

  root :to => 'map#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :registerable, and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      redirect_to admin_users_path, notice: 'User was successfully created.'
    else
      render action: 'new', error: 'There was a problem saving the user.'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if params[:user][:password].empty? and params[:user][:password_confirmation].empty?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end
    if @user.update_attributes(params[:user])
      sign_in(@user, :bypass => true) if @user == current_user
      redirect_to admin_users_path, notice: 'User was successfully updated.'
    else
      redirect_to edit_admin_user_path(@user), alert: 'There was a problem saving the user.'
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      redirect_to admin_users_path, notice: 'User was successfully deleted.'
    else
      redirect_to edit_admin_user_path(@user), alert: 'There was a problem deleting the user.'
    end
  end
end

app/views/admin/users/_form.haml
= simple_form_for [:admin, @user], html: { class: 'form-horizontal' } do |f|
  - if @user.errors.any?
    #error_explanation
      %h3
        = pluralize(@user.errors.count, "error")
        prohibited this user from being saved:
      %ul.validation_errors
        - @user.errors.full_messages.each do |msg|
          %li= msg

  - if params[:action] == 'edit'
    .form-group
      .col-sm-10.col-sm-offset-2
        = image_tag avatar_url(@user, 150)

  .form-group
    = f.label :email, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.input_field :email, class: 'form-control'

  - if params[:action] == 'edit'
    .form-group
      = f.label :last_sign_in_at, class: 'col-sm-2 control-label'
      .col-sm-10
        %div(style="padding: 6px 0")= f.object.last_sign_in_at

    .form-group
      = f.label :last_sign_in_ip, class: 'col-sm-2 control-label'
      .col-sm-10
        %div(style="padding: 6px 0")= f.object.last_sign_in_ip

    .form-group
      = f.label :created_at, class: 'col-sm-2 control-label'
      .col-sm-10
        %div(style="padding: 6px 0")= f.object.created_at

  .form-group
    - if params[:action] == 'edit'
      .col-sm-10.col-sm-offset-2
        %p
          %em Leave password blank to keep it unchanged.

  .form-group
    = f.label :password, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.input_field :password, class: 'form-control'

  .form-group
    = f.label :password_confirmation, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.input_field :password_confirmation, class: 'form-control'

  .form-group.actions
    .col-sm-offset-2.col-sm-10
      = f.button :submit, 'Submit'
      - if params[:action] == 'edit'
        %p.delete-link
          = link_to 'Delete User', admin_user_path, method: :delete, data: { confirm: 'Are you sure you want to delete this user?' }

app/views/admin/users/edit.haml
%h1
  %span.text-muted Editing User
  %span= @user.email

= render 'form'

app/views/admin/users/index.haml
%h1 Users

%p
  = link_to new_admin_user_path do
    %span.glyphicon.glyphicon-plus
    New User

%table.table.table-striped.table-bordered
  %thead
    %tr
      %th Email
      %th Last Login
  %tbody
    - @users.each do |user|
      %tr
        %td= link_to user.email, edit_admin_user_path(user)
        %td= user.last_sign_in_at

app/views/admin/users/new.haml
%h1
  %span.text-muted New User

= render 'form'