config/routes.rb
FoodTruckMap::Application.routes.draw do
  devise_for :users,  controllers: { sessions: 'admin/sessions' }

  namespace :admin do
    resources :users
    resources :food_trucks

    get '/' => 'dashboard#index'
  end

  scope 'api' do
    resources :food_trucks
    resources :tags
  end

  root :to => 'map#index'
end

app/views/layouts/admin.haml
!!! HTML
%html
  %head
    %title= ENV['INSTANCE_TITLE'] || 'Food Truck Map'
    = stylesheet_link_tag 'admin', media: 'all'
    = csrf_meta_tags
  %body
    %nav(class="navbar navbar-default" role="navigation")
      %div.container
        %div.navbar-header
          %button(type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse")
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a(class="navbar-brand")= ENV['INSTANCE_TITLE'] || 'Food Truck Map'
        - if user_signed_in?
          %div(class="collapse navbar-collapse navbar-ex1-collapse")
            %ul(class="nav navbar-nav")
              %li{class: ('active' if params[:controller] == 'admin/dashboard')}
                = link_to 'Dashboard', admin_path()
              %li{class: ('active' if params[:controller] == 'admin/food_trucks')}
                = link_to 'Food Trucks', admin_food_trucks_path()
              %li{class: ('active' if params[:controller] == 'admin/users')}
                = link_to 'Users', admin_users_path()
            %ul(class="nav navbar-nav navbar-right")
              %li
                %a(href='#') Profile
              %li= link_to 'Logout', destroy_user_session_path, method: :delete
    %div.container
      = bootstrap_flash
      = yield
    = javascript_include_tag 'admin'

app/views/layouts/application.haml
!!!
%html
  %head
    %meta{charset: "utf-8"}/
    %meta{content: "IE=edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
    %title= ENV['INSTANCE_TITLE'] || 'Food Truck Map'
    = stylesheet_link_tag 'application', media: 'all'
    = csrf_meta_tags
  %body{"ng-app" => "food_truck_app", "ng-controller" => "food_trucks_controller as food_trucks"}
    .container.fill-height
      .row.fill-height
        .fill-height.col-sm-3.navigation
          %h1
            = link_to 'Food Truck Map', root_path
            %span.beta BETA
          = yield
        #map.col-sm-9.fill-height
    = javascript_include_tag 'application'
    :javascript
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
      ga('create', 'UA-43961581-2', 'seattlefoodtrucks.herokuapp.com');
      ga('send', 'pageview');